<?php
/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function logo_options_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function logo_options_add_meta_box() {
	add_meta_box(
		'logo_options-logo-options',
		__( 'Logo options', 'logo_options' ),
		'logo_options_html',
		'holiday_logos',
		'normal',
		'default'
	);
}
add_action( 'add_meta_boxes', 'logo_options_add_meta_box' );

function logo_options_html( $post ) {
	/**
	 * Enqueue Datepicker + jQuery UI CSS
	 * https://www.designbyhn.se/adding-a-datepicker-to-a-wordpress-metabox/
	 */
	wp_enqueue_script( 'jquery-ui-datepicker' );
	wp_enqueue_style( 'jquery-ui-style', '//ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/themes/smoothness/jquery-ui.css', true);

	wp_nonce_field( '_logo_options_nonce', 'logo_options_nonce' ); ?>

	<script>
	jQuery( document ).ready(function() {
		jQuery( '.hls_date' ).datepicker({
			dateFormat : 'dd/mm/yy'
		});
	});
	</script>

	<p>
		<label for="logo_options_from_date_"><?php _e( 'From (date)', 'logo_options' ); ?></label><br>
		<input type="text" name="logo_options_from_date_" class="hls_date" id="logo_options_from_date_" value="<?php echo logo_options_get_meta( 'logo_options_from_date_' ); ?>">
	</p>	<p>
		<label for="logo_options_to_date_"><?php _e( 'To (date)', 'logo_options' ); ?></label><br>
		<input type="text" name="logo_options_to_date_" class="hls_date" id="logo_options_to_date_" value="<?php echo logo_options_get_meta( 'logo_options_to_date_' ); ?>">
	</p>	<p>
		<label for="logo_options_image_alt"><?php _e( 'Image Alt', 'logo_options' ); ?></label><br>
		<input type="text" name="logo_options_image_alt" id="logo_options_image_alt" value="<?php echo logo_options_get_meta( 'logo_options_image_alt' ); ?>">
	</p><?php
}

function logo_options_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['logo_options_nonce'] ) || ! wp_verify_nonce( $_POST['logo_options_nonce'], '_logo_options_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['logo_options_from_date_'] ) )
		update_post_meta( $post_id, 'logo_options_from_date_', esc_attr( $_POST['logo_options_from_date_'] ) );
	if ( isset( $_POST['logo_options_to_date_'] ) )
		update_post_meta( $post_id, 'logo_options_to_date_', esc_attr( $_POST['logo_options_to_date_'] ) );
	if ( isset( $_POST['logo_options_image_alt'] ) )
		update_post_meta( $post_id, 'logo_options_image_alt', esc_attr( $_POST['logo_options_image_alt'] ) );
}
add_action( 'save_post', 'logo_options_save' );

/*
	Usage: logo_options_get_meta( 'logo_options_from_date_' )
	Usage: logo_options_get_meta( 'logo_options_to_date_' )
	Usage: logo_options_get_meta( 'logo_options_image_alt' )
*/
